-- =====================================================================
-- YIQ seed — edition, topics, chapter events, question bank.
-- Question TEXT and ANSWERS are verbatim from the Director's deck
-- (YIQ.pptx, slides 8-11). The three distractors on each MCQ are
-- authored for this platform and need a content review before go-live.
--
-- DELIBERATELY NOT SEEDED (flagged to the Director 2026-08-24):
--   * "Who is the current Governor of RBI?" - the deck answers
--     "Sanjay Malhotra (as of 2025)"; time-sensitive, needs re-check.
--   * "India's rank in 2024 Paris Olympics medal tally?" - the deck
--     itself says "To be updated annually".
--   * "Which Indian won the 2024 Nobel Prize (if any)?" - the deck
--     itself says "Updated each year".
--   * "Who holds the record for most ODI centuries?" - the deck answers
--     "Sachin Tendulkar (49)", which is out of date: Virat Kohli passed
--     that mark in Nov 2023. Needs the Director's ruling before use.
--   * The deck frames Jama Masjid as a "UNESCO heritage site"; it is
--     India's largest mosque but is not an inscribed UNESCO WHS, so the
--     seeded question drops the UNESCO clause.
-- =====================================================================

insert into yiq.editions (name, yi_year, slug, is_active,
  registration_opens_at, registration_closes_at,
  online_round_opens_at, online_round_closes_at,
  national_semifinal_at, national_finale_at)
values ('YIQ 2026-27', 2026, 'yiq-2026-27', true,
  '2026-07-01 00:00:00+05:30', '2026-09-15 23:59:59+05:30',
  '2026-09-20 00:00:00+05:30', '2026-10-31 23:59:59+05:30',
  '2027-01-15 00:00:00+05:30', '2027-02-20 00:00:00+05:30')
on conflict (slug) do nothing;

-- Topics (deck slide 7)
insert into yiq.topics (slug, name, description, display_order) values ('india', 'India', 'History, Geography, Culture, Constitution, Parliament', 1) on conflict (slug) do nothing;
insert into yiq.topics (slug, name, description, display_order) values ('young-india-leadership', 'Young India & Leadership', 'Startups, Innovation, Social Impact', 2) on conflict (slug) do nothing;
insert into yiq.topics (slug, name, description, display_order) values ('business-economics', 'Business & Economics', 'GDP, Markets, Banking, Finance, Trade', 3) on conflict (slug) do nothing;
insert into yiq.topics (slug, name, description, display_order) values ('science-technology', 'Science & Technology', 'AI, Space, Medicine, Environment', 4) on conflict (slug) do nothing;
insert into yiq.topics (slug, name, description, display_order) values ('current-affairs', 'Current Affairs', 'National, International, Sports, Business', 5) on conflict (slug) do nothing;
insert into yiq.topics (slug, name, description, display_order) values ('sports', 'Sports', 'Olympics, Cricket, Chess, Football, Indian Sports', 6) on conflict (slug) do nothing;
insert into yiq.topics (slug, name, description, display_order) values ('arts-culture', 'Arts & Culture', 'Music, Cinema, Literature, Dance, Architecture', 7) on conflict (slug) do nothing;

-- One chapter_event per active Yi chapter for the active edition.
insert into yiq.chapter_events (edition_id, chapter_name, yi_zone, status,
  qualifying_team_count)
select e.id, c.name, c.region, 'registration_open', 10
from yiq.editions e
cross join yi.chapters c
where e.slug = 'yiq-2026-27' and c.is_active = true
on conflict (edition_id, chapter_name) do nothing;

-- Question bank

insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Who was the first Deputy Prime Minister of India?', 'Sardar Vallabhbhai Patel', 'Jawaharlal Nehru', 'Dr. Rajendra Prasad', 'Maulana Abul Kalam Azad', 'a', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'india' and not exists (select 1 from yiq.questions x where x.question_text = 'Who was the first Deputy Prime Minister of India?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Which river is known as ''Dakshin Ganga'' (Ganges of the South)?', 'Krishna', 'Godavari', 'Kaveri', 'Narmada', 'b', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'india' and not exists (select 1 from yiq.questions x where x.question_text = 'Which river is known as ''Dakshin Ganga'' (Ganges of the South)?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'How many Fundamental Duties are listed in the Indian Constitution?', '9', '10', '11', '12', 'c', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'india' and not exists (select 1 from yiq.questions x where x.question_text = 'How many Fundamental Duties are listed in the Indian Constitution?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Which Article of the Constitution abolishes untouchability?', 'Article 14', 'Article 15', 'Article 21', 'Article 17', 'd', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'india' and not exists (select 1 from yiq.questions x where x.question_text = 'Which Article of the Constitution abolishes untouchability?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Who designed the National Flag of India?', 'Pingali Venkayya', 'Rabindranath Tagore', 'Bankim Chandra Chatterjee', 'Nandalal Bose', 'a', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'india' and not exists (select 1 from yiq.questions x where x.question_text = 'Who designed the National Flag of India?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'The term ''Secular'' was added to the Preamble by which Amendment?', '44th Constitutional Amendment, 1978', '42nd Constitutional Amendment, 1976', '24th Constitutional Amendment, 1971', '52nd Constitutional Amendment, 1985', 'b', 'hard', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'india' and not exists (select 1 from yiq.questions x where x.question_text = 'The term ''Secular'' was added to the Preamble by which Amendment?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Which is the southernmost point of mainland India?', 'Indira Point', 'Rameswaram', 'Kanyakumari (Cape Comorin)', 'Dhanushkodi', 'c', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'india' and not exists (select 1 from yiq.questions x where x.question_text = 'Which is the southernmost point of mainland India?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Who founded Infosys in 1981?', 'Azim Premji', 'Shiv Nadar', 'Ratan Tata', 'N.R. Narayana Murthy', 'd', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'young-india-leadership' and not exists (select 1 from yiq.questions x where x.question_text = 'Who founded Infosys in 1981?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Which Indian founded Paytm?', 'Vijay Shekhar Sharma', 'Bhavish Aggarwal', 'Sachin Bansal', 'Byju Raveendran', 'a', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'young-india-leadership' and not exists (select 1 from yiq.questions x where x.question_text = 'Which Indian founded Paytm?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'What is a ''Unicorn'' in the startup world?', 'A startup valued at $100 million or more', 'A startup valued at $1 billion or more', 'A startup valued at $10 billion or more', 'A startup profitable in its first year', 'b', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'young-india-leadership' and not exists (select 1 from yiq.questions x where x.question_text = 'What is a ''Unicorn'' in the startup world?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Zerodha was founded by which brothers?', 'Sachin and Binny Bansal', 'Ritesh and Rahul Agarwal', 'Nithin and Nikhil Kamath', 'Deepinder and Pankaj Goyal', 'c', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'young-india-leadership' and not exists (select 1 from yiq.questions x where x.question_text = 'Zerodha was founded by which brothers?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Who was the first Indian woman to reach the summit of Mt. Everest?', 'Santosh Yadav', 'Arunima Sinha', 'Premlata Agrawal', 'Bachendri Pal (1984)', 'd', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'young-india-leadership' and not exists (select 1 from yiq.questions x where x.question_text = 'Who was the first Indian woman to reach the summit of Mt. Everest?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'What does RBI stand for?', 'Reserve Bank of India', 'Regional Bank of India', 'Rural Bank of India', 'Royal Bank of India', 'a', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'business-economics' and not exists (select 1 from yiq.questions x where x.question_text = 'What does RBI stand for?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Which document is called the ''Financial Statement of the Government''?', 'Economic Survey', 'Union Budget', 'Finance Bill', 'Annual Financial Report', 'b', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'business-economics' and not exists (select 1 from yiq.questions x where x.question_text = 'Which document is called the ''Financial Statement of the Government''?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'What does GDP stand for?', 'Gross Development Product', 'General Domestic Produce', 'Gross Domestic Product', 'Gross Domestic Profit', 'c', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'business-economics' and not exists (select 1 from yiq.questions x where x.question_text = 'What does GDP stand for?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Who is known as the ''Father of the Green Revolution'' in India?', 'Verghese Kurien', 'Norman Borlaug', 'C. Subramaniam', 'M.S. Swaminathan', 'd', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'business-economics' and not exists (select 1 from yiq.questions x where x.question_text = 'Who is known as the ''Father of the Green Revolution'' in India?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'What is the main stock exchange index of the Bombay Stock Exchange?', 'SENSEX', 'NIFTY 50', 'BANKEX', 'MIDCAP', 'a', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'business-economics' and not exists (select 1 from yiq.questions x where x.question_text = 'What is the main stock exchange index of the Bombay Stock Exchange?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Which organisation launched Chandrayaan-3?', 'DRDO', 'ISRO', 'NASA', 'HAL', 'b', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'science-technology' and not exists (select 1 from yiq.questions x where x.question_text = 'Which organisation launched Chandrayaan-3?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'What does AI stand for?', 'Automated Intelligence', 'Applied Informatics', 'Artificial Intelligence', 'Advanced Integration', 'c', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'science-technology' and not exists (select 1 from yiq.questions x where x.question_text = 'What does AI stand for?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'What is India''s first indigenously built aircraft carrier?', 'INS Viraat', 'INS Vikramaditya', 'INS Arihant', 'INS Vikrant', 'd', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'science-technology' and not exists (select 1 from yiq.questions x where x.question_text = 'What is India''s first indigenously built aircraft carrier?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', '''ChatGPT'' is an example of what?', 'A Large Language Model (LLM) / Generative AI', 'A search engine', 'An operating system', 'A relational database', 'a', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'science-technology' and not exists (select 1 from yiq.questions x where x.question_text = '''ChatGPT'' is an example of what?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Chandrayaan-3 soft-landed near which lunar region?', 'The North Pole of the Moon', 'The South Pole of the Moon', 'The Sea of Tranquillity', 'The equator on the far side', 'b', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'science-technology' and not exists (select 1 from yiq.questions x where x.question_text = 'Chandrayaan-3 soft-landed near which lunar region?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Which nation hosted the G20 Summit in 2023?', 'Indonesia', 'Brazil', 'India (New Delhi)', 'Italy', 'c', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'current-affairs' and not exists (select 1 from yiq.questions x where x.question_text = 'Which nation hosted the G20 Summit in 2023?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Name the Prime Minister-led initiative for digital infrastructure in India.', 'Make in India', 'Skill India', 'Startup India', 'Digital India', 'd', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'current-affairs' and not exists (select 1 from yiq.questions x where x.question_text = 'Name the Prime Minister-led initiative for digital infrastructure in India.');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Who was India''s first individual Olympic Gold Medallist?', 'Abhinav Bindra (2008, 10m Air Rifle)', 'Neeraj Chopra', 'K.D. Jadhav', 'Sushil Kumar', 'a', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'sports' and not exists (select 1 from yiq.questions x where x.question_text = 'Who was India''s first individual Olympic Gold Medallist?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'India won its first Chess Olympiad Gold in which year?', '2022 (Chennai)', '2024 (Budapest)', '2018 (Batumi)', '2020 (Online)', 'b', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'sports' and not exists (select 1 from yiq.questions x where x.question_text = 'India won its first Chess Olympiad Gold in which year?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Who became the youngest World Chess Champion?', 'Magnus Carlsen', 'Garry Kasparov', 'Gukesh D (2024)', 'Viswanathan Anand', 'c', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'sports' and not exists (select 1 from yiq.questions x where x.question_text = 'Who became the youngest World Chess Champion?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'The Durand Cup is associated with which sport?', 'Hockey', 'Cricket', 'Badminton', 'Football', 'd', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'sports' and not exists (select 1 from yiq.questions x where x.question_text = 'The Durand Cup is associated with which sport?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Who wrote India''s National Anthem ''Jana Gana Mana''?', 'Rabindranath Tagore', 'Bankim Chandra Chatterjee', 'Sarojini Naidu', 'Muhammad Iqbal', 'a', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'arts-culture' and not exists (select 1 from yiq.questions x where x.question_text = 'Who wrote India''s National Anthem ''Jana Gana Mana''?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Which Indian filmmaker won the Academy Honorary Award in 1992?', 'Mrinal Sen', 'Satyajit Ray', 'Ritwik Ghatak', 'Guru Dutt', 'b', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'arts-culture' and not exists (select 1 from yiq.questions x where x.question_text = 'Which Indian filmmaker won the Academy Honorary Award in 1992?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Bharatanatyam is a classical dance form originating from which state?', 'Kerala', 'Andhra Pradesh', 'Tamil Nadu', 'Odisha', 'c', 'easy', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'arts-culture' and not exists (select 1 from yiq.questions x where x.question_text = 'Bharatanatyam is a classical dance form originating from which state?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Who composed the music for the film ''Mughal-E-Azam''?', 'S.D. Burman', 'Shankar-Jaikishan', 'Madan Mohan', 'Naushad Ali', 'd', 'hard', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'arts-culture' and not exists (select 1 from yiq.questions x where x.question_text = 'Who composed the music for the film ''Mughal-E-Azam''?');
insert into yiq.questions (topic_id, category, question_type, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, source) select t.id, 'both', 'mcq', 'Which is India''s largest mosque?', 'Jama Masjid, Delhi', 'Taj-ul-Masajid, Bhopal', 'Mecca Masjid, Hyderabad', 'Charminar, Hyderabad', 'a', 'medium', 'YIQ deck 2026 (sample questions)' from yiq.topics t where t.slug = 'arts-culture' and not exists (select 1 from yiq.questions x where x.question_text = 'Which is India''s largest mosque?');
