-- =====================================================================
-- YIQ — a REASONING question bank, replacing recall as the house style.
--
-- WHY (Director ruling, 2026-08-27, on the "YIQ Chapter Level" paper).
--
-- The bank this platform shipped with is 195 general-knowledge RECALL
-- questions: "Which city is the Pink City?", "What is the repo rate?",
-- "Har Gobind Khorana's Nobel category?". Classes 9 to 12 sit the same
-- competition, and the existing answer to that spread was to SPLIT the
-- paper into a junior one and a senior one — then rank both on one
-- national ladder. Those scores are not comparable, and a Class 9
-- student loses to a Class 12 student on syllabus exposure rather than
-- on thinking.
--
-- The Chapter Level paper the Director supplied fixes this at the root.
-- Its own instruction line: questions "emphasize reasoning,
-- interpretation, observation and broad awareness rather than
-- senior-class syllabus depth". A Class 9 student and a Class 12
-- student meet a question like "5 machines make 5 parts in 5 minutes;
-- how many do 20 machines make in 20 minutes?" on equal terms.
--
-- WHAT THIS MIGRATION DOES NOT DO — and deliberately so:
--
--   * It does NOT collapse Junior and Senior. The deck makes them
--     SEPARATE CHAMPIONSHIPS all the way to the National Grand Finale,
--     and `category` is load-bearing on five tables (questions, papers,
--     teams, national_entries, finals_rounds). Reasoning questions are
--     compatible with keeping both championships — they make each one
--     internally fair, which is the actual problem. Merging the two is
--     a separate decision for the Director, not a side effect of a
--     question-bank change.
--
--   * It does NOT retire the 195 recall questions. They stay active and
--     usable. Retiring a bank the September round may still fall back
--     on, four weeks out, is not a change to make in the same breath as
--     adding its replacement. Retire them once a chapter has actually
--     run on the new style.
--
--   * It does NOT put these questions into competition. Every row lands
--     as pool='practice' with is_ai_generated=true and reviewed_at NULL.
--     That is Director rule 7 ("the bank grows by AI draft + HUMAN
--     approval") honoured literally: these were drafted by a model and
--     no person at Yi has read them yet. `yiq_questions_ai_needs_review`
--     enforces exactly this — a competition-pool AI row without a
--     reviewed_at is rejected by the database.
--
--     The immediate win is still real: the practice pool goes from 33
--     questions to 33 + these, which was open gap #3 (students exhaust
--     practice before the round even opens).
--
-- ON VISUAL QUESTIONS. The source paper has eight, and three of its
-- eight images are broken in the PDF as supplied (Q29 renders as four
-- solid black boxes with no dots — unanswerable as printed; Q34's clock
-- has no hands; Q36's map is a black rectangle). No image is authored
-- here. Every spatial question below is written to be answerable from
-- its own text, the way the source paper's Q32 is. media_url stays NULL
-- and the quiz client already renders it when a real image exists.
--
-- ON TIMERS. The source paper puts a per-question timer on every
-- question (15s to 32s). This platform has ONE clock for the whole
-- paper; only finals_rounds carry time_limit_seconds. Per-question
-- timing is a real build and is NOT attempted here. Worth knowing
-- before it is: the source paper's own timers sum to 1,142 seconds =
-- 19 minutes, against a stated total of 30.
--
-- Every answer below was worked out and is recorded in
-- answer_explanation — which is what the human reviewer checks against,
-- and what the student sees on the review screen after the paper.
-- =====================================================================

do $$
declare
  t_india    uuid := '4f0c93df-24c5-4c84-a638-a2bd1ce76f8d';
  t_sci      uuid := 'bbbda800-904c-4e8d-9d2b-ae25991ce164';
  t_econ     uuid := '7b3f9a52-9e64-43de-8f7d-79ab59452116';
  t_arts     uuid := '64ecc187-a16e-445f-bd5d-a813dc26b103';
  t_current  uuid := '71055337-248a-4bf8-943e-7f8dd0f27d1b';
  t_sport    uuid := '6647727d-9a0c-4f49-b426-d07116fae1a4';
  t_young    uuid := '70f1ce6e-dbed-461b-9354-7651ab53c136';
begin

  -- IDEMPOTENT. These rows carry no natural key, so a second run would
  -- silently double the bank. Bail out loudly instead.
  if exists (select 1 from yiq.questions
             where source like 'YIQ Reasoning Bank 2026%') then
    raise notice 'YIQ reasoning bank already present - nothing inserted.';
    return;
  end if;

-- ── BRAIN SPRINT ─────────────────────────────────────────────────────
-- Fast arithmetic, proportion and pattern. Nothing to memorise; the only
-- question is whether the student can see it quickly.
insert into yiq.questions (
  topic_id, category, question_type, question_text,
  option_a, option_b, option_c, option_d, correct_option,
  answer_explanation, difficulty, source, pool,
  is_ai_generated, reviewed_at, is_active, is_retired
) values
(t_sci,'both','mcq','If n leaves remainder 3 when divided by 7, which of these must be divisible by 7?','n+4','n+2','n+3','2n+3','a','n = 7k+3, so n+4 = 7k+7 = 7(k+1). Only adding 4 completes the next multiple of 7.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','A patch of lilies doubles in area every day and covers the whole pond on day 20. On which day was the pond half covered?','Day 10','Day 19','Day 18','Day 15','b','Doubling backwards once from full gives half. If it is full on day 20 it was half on day 19 - not day 10, which is the trap.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','Barometer : pressure has the same relationship as:','Compass : speed','Telescope : light','Odometer : distance','Kettle : water','c','A barometer measures pressure; an odometer measures distance. Both are instrument-to-quantity.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','If 4x+7 = 2x+19, then x equals:','4','13','9','6','d','Subtract 2x from both sides: 2x+7 = 19, so 2x = 12 and x = 6.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','Which change increases a square''s area by exactly 44%?','Increase each side by 20%','Increase each side by 22%','Increase each side by 44%','Increase one side by 44%','a','Area scales as the square of the side. 1.20 x 1.20 = 1.44, a 44% rise. Raising each side 22% would give 1.4884.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','Shifting each letter forward by two places turns MIND into:','NJOE','OKPF','LHMC','PLQG','b','M to O, I to K, N to P, D to F. Each letter moves two places on.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','An astronaut travels from Earth to the Moon. Which of these changes?','Mass','Number of atoms','Weight','Chemical composition','c','Weight is mass times local gravity, and lunar gravity is weaker. Mass, atom count and composition are unchanged by location.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','In a class of 50, 70% wear glasses. How many do NOT?','10','35','20','15','d','30% do not wear glasses, and 30% of 50 is 15. The trap is answering 35, the number who do.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','Which is always true of a rhombus?','All four sides are equal','All angles are equal','The diagonals are equal','It has exactly one pair of parallel sides','a','A rhombus is defined by four equal sides. Its angles need not be equal (that would be a square) and its diagonals differ in length.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','A quantity increases from 60 to 75. What is the percentage increase?','15%','25%','20%','30%','b','The rise is 15, measured against the ORIGINAL 60: 15/60 = 25%. Dividing by 75 instead gives the trap answer 20%.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','25% of 80 is what percentage of 50?','20%','25%','40%','50%','c','25% of 80 is 20. Then 20 out of 50 is 40%. Two steps, and the second is the one people skip.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','Two numbers are in the ratio 3:5 and add up to 64. The smaller number is:','21','40','27','24','d','The parts total 8, so one part is 64/8 = 8. The smaller number is 3 parts = 24.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','The sequence runs 2, 6, 12, 20, 30. What comes next?','42','40','36','44','a','The gaps are 4, 6, 8, 10 - each two more than the last. The next gap is 12, so 30+12 = 42.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','If today is Wednesday, what day falls 30 days from now?','Thursday','Friday','Saturday','Sunday','b','30 divided by 7 leaves remainder 2. Two days past Wednesday is Friday. Only the remainder matters.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','At exactly 6:00, the angle between a clock''s hands is:','90 degrees','120 degrees','180 degrees','360 degrees','c','The hour hand is on 6 and the minute hand on 12 - directly opposite, which is half a full turn.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_econ,'both','mcq','An item costing 200 rupees is sold for 250. The profit percentage is:','20%','50%','40%','25%','d','Profit is 50, measured against the COST of 200: 50/200 = 25%. Measuring against the selling price gives the trap 20%.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','Three consecutive whole numbers add up to 48. The middle one is:','16','15','17','18','a','For three consecutive numbers the middle one is always the average: 48/3 = 16.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','A square has a perimeter of 36 cm. Its area is:','36 sq cm','81 sq cm','49 sq cm','144 sq cm','b','Each side is 36/4 = 9 cm, so the area is 9 x 9 = 81 square centimetres.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','A bus travels at a steady 60 km/h for 45 minutes. How far does it go?','40 km','50 km','45 km','60 km','c','45 minutes is three quarters of an hour, and three quarters of 60 km is 45 km.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_econ,'both','mcq','A shop offers 25% off an 800-rupee jacket. What do you pay?','575','650','625','600','d','25% of 800 is 200, so you pay 800 - 200 = 600.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','Which of these is the largest?','0.707','0.07','0.7','0.077','a','Compare place by place: 0.707 beats 0.7 at the thousandths, and both beat 0.07 and 0.077 at the tenths.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','How many edges does a cube have?','6','12','8','16','b','A cube has 6 faces, 8 corners and 12 edges - three meeting at each of the eight corners, each shared by two.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','If 20% of a number is 40, the number is:','80','120','200','160','c','If one fifth is 40, the whole is 5 x 40 = 200.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_arts,'both','mcq','Chapter : book has the same relationship as:','Author : novel','Film : cinema','Library : book','Scene : film','d','A chapter is a division within a book, as a scene is a division within a film. The others reverse the direction or change it.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','What is 7 squared minus 5 squared?','24','12','20','35','a','49 - 25 = 24. (It also equals (7+5)(7-5) = 12 x 2.)','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','How many prime numbers are there below 10?','3','4','5','6','b','2, 3, 5 and 7 - four of them. 1 is not prime and 9 is 3 x 3.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','If 6 identical pens cost 90 rupees, what do 10 cost?','120','135','150','160','c','One pen costs 90/6 = 15, so ten cost 150.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','Half of one quarter is:','1/2','1/6','1/16','1/8','d','Half of 1/4 means 1/2 x 1/4 = 1/8.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','The smallest number that both 4 and 6 divide into is:','12','8','18','24','a','Multiples of 4: 4, 8, 12. Multiples of 6: 6, 12. The first they share is 12.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','The largest number that divides both 12 and 18 exactly is:','2','6','3','9','b','6 divides 12 (twice) and 18 (three times). 9 does not divide 12.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','A number is doubled and then reduced by 10, giving 30. The number was:','15','25','20','40','c','Work backwards: 30 + 10 = 40, then 40/2 = 20.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','The average of 10, 20, 30 and 40 is:','20','35','30','25','d','Their total is 100 and there are four of them, so the average is 25.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','A rectangle is 12 cm by 5 cm. Its diagonal is:','13 cm','15 cm','17 cm','7 cm','a','The diagonal completes a right-angled triangle: 12 squared + 5 squared = 144 + 25 = 169, and the square root of 169 is 13.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','If a = 2 and b = 3, what is a cubed plus b squared?','13','17','19','25','b','2 cubed is 8 and 3 squared is 9, giving 17. The trap is squaring both.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','A wheel makes 4 complete turns. Through how many degrees has it rotated?','360','720','1440','1080','c','Each full turn is 360 degrees, so four turns is 4 x 360 = 1440.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_econ,'both','mcq','A price rises by 10% and then falls by 10%. Compared with the start, the final price is:','The same','Higher','10% lower','1% lower','d','1.10 x 0.90 = 0.99. The fall is taken on a bigger number than the rise was, so you end 1% down.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','Which fraction is closest to 1?','7/8','3/4','5/6','9/11','a','7/8 = 0.875, ahead of 5/6 = 0.833, 9/11 = 0.818 and 3/4 = 0.75.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','The sequence runs 1, 4, 9, 16, 25. What comes next?','30','36','35','49','b','These are the square numbers: 1, 2, 3, 4, 5 squared. Next is 6 squared = 36.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','A two-digit number is 47. Subtracting it from its reverse gives:','36','29','27','18','c','The reverse is 74, and 74 - 47 = 27. (Reversing always gives a multiple of 9 times the digit gap.)','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false),
(t_sci,'both','mcq','How many minutes are there in one-eighth of a day?','120','360','240','180','d','A day is 1440 minutes, and 1440/8 = 180.','easy','YIQ Reasoning Bank 2026 - BRAIN SPRINT','practice',true,null,true,false);

-- ── DON''T GOOGLE THIS ────────────────────────────────────────────────
-- Everyday physics you can reason your way to from things you have seen.
-- Looking these up is slower than thinking about them.
insert into yiq.questions (
  topic_id, category, question_type, question_text,
  option_a, option_b, option_c, option_d, correct_option,
  answer_explanation, difficulty, source, pool,
  is_ai_generated, reviewed_at, is_active, is_retired
) values
(t_sci,'both','mcq','Equal amounts of hot tea are poured into a wide shallow cup and a narrow deep one. Which usually cools faster?','The wide one - more surface is exposed to the air','The narrow one - it is deeper','Exactly the same','The narrow one - less heat to start with','a','Cooling happens at the surface. A wide cup exposes far more tea to the air, so it loses heat faster despite holding the same amount.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A lift starts moving upward and a bathroom scale inside briefly reads higher. Why?','Your mass increases','The floor pushes harder to accelerate you upward','Gravity increases','Air pressure rises','b','To accelerate you upward the floor must push with more than your weight. The scale reads that push, not your mass, which has not changed.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Why does a black surface get hotter than a white one in the same sunlight?','It is closer to the Sun','It creates extra heat','It absorbs more of the light falling on it','White surfaces produce cold','c','A dark surface absorbs most of the light and converts it to heat; a white one reflects most of it away.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A metal lid on a glass jar loosens after warm water is run over it. Mainly because:','The glass shrinks instantly','The metal becomes lighter','Friction disappears in water','The metal expands more than the glass','d','Both expand, but metal expands considerably more than glass for the same temperature rise, so the lid grows away from the neck.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A flat sheet of paper and an identical crumpled sheet are dropped together. The crumpled one usually lands first because:','It meets far less air resistance for its weight','It is heavier','Gravity ignores flat paper','Flat paper is weightless','a','Crumpling does not change the weight but greatly reduces the area meeting the air, so drag slows it much less.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Why do stars appear to twinkle much more than planets?','Stars switch brightness on and off','Air currents bend light across their point-like image','Planets give out no light','Clouds magnify stars','b','A star is effectively a point, so moving air deflects its whole image at once. A planet is a small disc, and the wobbles across it average out.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','You feel cold stepping out of a swimming pool even on a warm day. Why?','The water was colder than the air','Your body stops producing heat','Evaporating water takes heat from your skin','Air pressure drops when wet','c','Evaporation carries away energy, and that energy comes from your skin. This is the same reason sweating cools you.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Lightning is seen before its thunder is heard because:','Eyes react faster than ears','Thunder starts later than the flash','Sound is blocked by clouds','Light travels far faster than sound','d','Both begin together. Light covers the distance almost instantly while sound takes about three seconds per kilometre.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A straw in a glass of water looks bent at the surface because:','Light changes direction as it passes between water and air','Water magnifies the straw','The straw actually bends','Glass distorts everything','a','Light travels at a different speed in water than in air, so it changes direction at the boundary. Your eye assumes it travelled straight.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Ice floats on water because:','Ice is lighter than all liquids','Water expands as it freezes, so ice is less dense','Ice contains trapped fish','Floating is caused by cold','b','Water is unusual: it expands on freezing. The same mass occupies more space, so ice is less dense than the water beneath it.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A bicycle pump gets warm while you inflate a tyre. Mainly because:','Friction with your hands','The tyre gives out heat','Compressing air heats it','Rubber generates warmth','c','Squeezing a gas into a smaller space raises its temperature. Friction in the pump adds a little, but compression is the main effect.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Food cooks faster in a pressure cooker because:','Pressure breaks food apart','Steam is hotter than fire','The lid traps flavour','The higher pressure raises water''s boiling point','d','Sealed in, the pressure rises and water boils above 100 degrees Celsius. The food therefore cooks at a higher temperature.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','You lean forward when a moving bus brakes suddenly because:','Your body keeps moving while the bus slows','The bus pushes you forward','Gravity shifts direction','Air pushes from behind','a','Nothing pushes you. Your body simply continues at the old speed until the seat and floor slow it - that tendency is inertia.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','The daytime sky is blue mainly because:','The sky reflects the oceans','Air scatters short blue wavelengths much more than red','The Sun emits only blue light','Blue is the colour of empty space','b','Air molecules scatter shorter wavelengths far more strongly, so blue light arrives at your eye from all over the sky.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Stars are invisible during the day because:','They stop shining','They move to the other side of Earth','Scattered sunlight in the atmosphere is far brighter than they are','Daylight destroys starlight','c','The stars are still there. The whole sky glows brighter than they do, so their light is lost against it.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Wet clothes dry faster on a windy day because:','Wind is warmer than still air','Moving air is drier by nature','Wind pushes water out of the fibres','Wind carries away the moist air sitting against the cloth','d','Still air right at the surface becomes saturated and drying stalls. Wind replaces it with drier air, so evaporation continues.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A knife is sharpened so that:','The same force acts over a smaller area, raising the pressure','The blade becomes heavier','It cuts with less total force needed','Metal becomes harder when thin','a','Pressure is force divided by area. A thin edge concentrates the same push into a tiny area, so it parts the material.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A steel ship floats although a steel nail sinks. The reason is:','Ships are made of lighter steel','The ship''s shape displaces enough water to match its weight','Sea water is denser than fresh water','Ships are hollow so they weigh nothing','b','Floating depends on the weight of water pushed aside, not on the material. A hull''s shape displaces a large volume; a solid nail displaces almost none.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','The Moon always shows Earth the same face because:','It does not rotate at all','Earth''s gravity holds one side still','It turns once on its axis in exactly the time it takes to orbit Earth','The far side is always dark','c','Its spin and its orbit take the same time, so the same hemisphere stays turned toward us. It certainly does rotate.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A burning candle covered by a glass jar goes out because:','The glass smothers the flame with cold','Light cannot escape','Carbon dioxide is flammable','The oxygen inside is used up','d','Burning consumes oxygen. Once the small trapped supply runs low the reaction cannot continue.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Salt is spread on icy roads because it:','Lowers the temperature at which water freezes','Warms the ice chemically','Makes ice rougher to grip','Absorbs the ice','a','Salty water freezes below zero degrees Celsius, so ice at just below freezing melts instead of staying solid.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A car windscreen fogs on the INSIDE on a cold day because:','Rain seeps through the glass','Warm moist air from inside condenses on the cold glass','The glass sweats','Cold air holds more water','b','Air inside is warm and carries moisture from breath. Touching cold glass it cools, can hold less, and the excess condenses.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Desert foxes have unusually large ears mainly to:','Hear predators further away only','Shade their eyes','Lose body heat through a large surface','Store water','c','Large thin ears carry a lot of blood close to a big surface, which sheds heat. Better hearing is a bonus, not the main reason.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A struck tuning fork sounds much louder when its base is pressed to a table because:','The table stores sound','The fork vibrates faster','Wood amplifies electricity','The table is set vibrating and moves far more air','d','The fork alone pushes very little air. Coupled to a large surface it makes the table vibrate, and the table moves much more air.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Sound travels faster in water than in air because:','Its particles are far closer together, passing the vibration on sooner','Water is wetter','Water has no resistance','Sound avoids air','a','A vibration passes from particle to particle. In a liquid they are packed close, so each one passes it on much sooner.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A mirror seems to swap your left and right but not your top and bottom. In fact a mirror reverses:','Left and right only','Front and back','Top and bottom too','Nothing at all','b','A mirror reverses the direction facing it. Your reflection''s nose points back at you; we describe that as a left-right swap only because we imagine turning ourselves around.','hard','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A hot-air balloon rises because the air inside is:','Heavier than the air outside','Under higher pressure','Less dense than the surrounding air','Chemically different','c','Heating air makes it expand, so the same volume weighs less than the cool air around it and the balloon is pushed up.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A metal spoon left in hot tea becomes hot at the handle. This happens by:','Convection','Evaporation','Radiation only','Conduction along the metal','d','Heat passes along the solid metal from particle to particle without the metal itself flowing - that is conduction.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A phone battery drains faster in very cold weather because:','The chemical reactions inside slow down','Cold drains electricity directly','Cold increases screen brightness','Batteries leak when cold','a','A battery works by chemistry, and chemical reactions run slower when cold, so it delivers less usable charge.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A rainbow appears when sunlight:','Bounces off clouds','Is bent and split into colours by water droplets','Is absorbed by rain','Reacts with dust','b','Each droplet bends the light, separates its colours by wavelength and reflects them back, so different colours reach you from different heights.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A heavily loaded truck takes much longer to stop than an empty one because:','Its brakes are weaker','Heavy vehicles have less grip by nature','Greater mass means more momentum to remove','Weight reduces friction','c','Stopping means removing momentum, which grows with mass. The same braking force takes longer to remove more of it.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','You are advised to wear light-coloured clothes in strong sun because they:','Block ultraviolet completely','Are always made of thinner cloth','Conduct heat out of the body','Reflect more of the sunlight away','d','Pale surfaces reflect most of the light instead of absorbing it as heat, so less warmth reaches you.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Sweating cools you mainly because:','Evaporating sweat carries heat away from the body','Sweat is colder than skin','Sweat blocks sunlight','Water conducts heat inward','a','It is the evaporation, not the wetness, that cools. This is why sweat cools you poorly in very humid air.','medium','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','A spinning football curves in flight because:','Spin makes it lighter','The air moves differently on the two sides, pushing it sideways','Gravity acts sideways on spin','The ball changes shape','b','A spinning surface drags air faster on one side than the other. The pressure difference across the ball pushes it off a straight path.','hard','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false),
(t_sci,'both','mcq','Two identical glasses hold water at 90 and 70 degrees Celsius in the same room. After ten minutes, which has lost MORE degrees?','Exactly the same','The 70-degree one','The 90-degree one','Impossible to say','c','The bigger the gap between an object and its surroundings, the faster it loses heat. The hotter glass starts with the bigger gap.','hard','YIQ Reasoning Bank 2026 - DONT GOOGLE THIS','practice',true,null,true,false);

-- ── CONNECT THE CLUES ────────────────────────────────────────────────
-- Four linked words. The student names the idea that ties them together.
-- Rewards seeing structure across subjects rather than recalling one fact.
insert into yiq.questions (
  topic_id, category, question_type, question_text,
  option_a, option_b, option_c, option_d, correct_option,
  answer_explanation, difficulty, source, pool,
  is_ai_generated, reviewed_at, is_active, is_retired
) values
(t_sci,'both','mcq','Zero - one - switches - computation','Genetics','Decimal system','Optics','Binary system','d','Two states, held by switches, are the basis of binary and of all digital computation.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Pressure - volume - gas - inverse relationship at constant temperature','Boyle''s law','Ohm''s law','Newton''s third law','Archimedes'' principle','a','Boyle''s law states that at a fixed temperature a gas''s pressure and volume vary inversely.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_india,'both','mcq','23.5 degrees North - India - Sun overhead near June','The Equator','Tropic of Cancer','Prime Meridian','Arctic Circle','b','The Tropic of Cancer sits at about 23.5 degrees North, crosses India, and marks where the Sun is overhead at the June solstice.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_econ,'both','mcq','Scarcity - choice - opportunity cost','Astronomy','Geometry','Economics','Ecology','c','Limited means force a choice, and the value of what you gave up is the opportunity cost - the founding chain of economics.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Mutation - selection - adaptation across generations','Refraction','Evaporation','Inflation','Evolution','d','Variation arises by mutation, selection favours some of it, and the population adapts over generations.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Encrypted message - key - sender - receiver','Cryptography','Cartography','Typography','Photography','a','A message scrambled with a key and unscrambled by the receiver is the basic shape of cryptography.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_india,'both','mcq','Legislature - executive - judiciary - checks and balances','Market competition','Separation of powers','Federal taxation','Universal suffrage','b','Splitting government into three branches that limit one another is the doctrine of separation of powers.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Hypothesis - evidence - repeatability - revision','Judicial review','Compound interest','Scientific method','Natural monopoly','c','Propose, test, check that others can repeat it, and revise - the working cycle of science.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_india,'both','mcq','Preamble - Fundamental Rights - Directive Principles','The Five Year Plans','The Union Budget','The Census','The Constitution of India','d','All three are parts of the Constitution: its statement of intent, its guaranteed rights and its guidance to the state.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_india,'both','mcq','Monsoon winds - Western Ghats - heavy rain on one side, dry on the other','Rain-shadow effect','Continental drift','Tidal range','Soil erosion','a','Air forced up a mountain range cools and drops its rain on the windward side, leaving a dry rain shadow beyond.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_econ,'both','mcq','Supply - demand - the price where they meet','Inflation','Market equilibrium','Depreciation','Subsidy','b','The equilibrium price is exactly the one at which the quantity offered equals the quantity wanted.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Producer - consumer - decomposer','An electrical circuit','A supply chain','A food chain','A water cycle','c','Energy passes from producers to consumers, and decomposers return the matter to the soil.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Chlorophyll - sunlight - carbon dioxide - glucose','Digestion','Respiration','Fermentation','Photosynthesis','d','Green plants use sunlight captured by chlorophyll to build glucose from carbon dioxide and water.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Sample - population - inference','Statistics','Trigonometry','Thermodynamics','Grammar','a','Statistics is the discipline of drawing conclusions about a whole population from a sample of it.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Plate boundary - fault line - sudden release of stress','Monsoon','Earthquake','Eclipse','Erosion','b','Stress builds where plates meet and is released suddenly along a fault, which is felt as an earthquake.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Compression - rarefaction - wavelength - medium','A radio antenna','A light wave','A sound wave','A magnetic field','c','Sound is a pressure wave of compressions and rarefactions and needs a medium - light does not.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Insulin - glucose - pancreas','Transport of oxygen','Digestion of protein','Filtration of blood','Regulation of blood sugar','d','The pancreas releases insulin, which lowers the level of glucose circulating in the blood.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Vaccine - antibody - immunity','Immunisation','Anaesthesia','Antisepsis','Transfusion','a','A vaccine trains the body to make antibodies, so it can respond quickly if it meets the real pathogen.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_econ,'both','mcq','Tariff - imported goods - protection of domestic industry','Free trade','Trade protectionism','Deflation','Privatisation','b','A tariff raises the price of imports so home-made goods can compete - the core tool of protectionism.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Ampere - volt - ohm','An optical lens','A sound system','An electric circuit','A chemical reaction','c','Current in amperes, potential difference in volts and resistance in ohms are the three quantities of a circuit.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_india,'both','mcq','Silt - distributary - fertile triangular plain at a river''s mouth','An estuary bar','A glacier','A plateau','A delta','d','A river slowing at its mouth drops silt and splits into distributaries, building the triangular land of a delta.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Precise steps - an input - a guaranteed stop','An algorithm','A hypothesis','A catalyst','A hierarchy','a','An algorithm is a finite sequence of unambiguous steps that acts on an input and is guaranteed to terminate.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_india,'both','mcq','Manifesto - constituency - ballot','A census','An election','A budget session','A judicial appeal','b','Parties publish a manifesto, candidates contest a constituency, and voters decide by ballot.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_young,'both','mcq','Entrepreneur - risk - venture - value created','Arbitration','Bureaucracy','Enterprise','Inheritance','c','An entrepreneur accepts risk to start a venture that creates value where none existed.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Satellite - orbit - gravity acting toward the centre','Nuclear fusion','Magnetic levitation','Buoyancy','Circular motion held by a centripetal force','d','Gravity supplies the inward force that continually bends a satellite''s path into an orbit.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_arts,'both','mcq','Raga - tala - improvisation within a framework','Indian classical music','Western opera','Folk theatre','Miniature painting','a','A raga sets the melodic frame and a tala the rhythmic cycle; the performer improvises inside them.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Latitude - altitude - distance from the sea','Ways of measuring time','Factors that shape climate','Types of soil','Units of pressure','b','How far from the equator, how high, and how near the sea are three of the main controls on a place''s climate.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Input - process - output - feedback','A fossil record','A monopoly','A system','An eclipse','c','Anything that takes input, transforms it, produces output and adjusts using feedback is a system.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_econ,'both','mcq','Principal - interest rate - maturity date','A stock split','A patent','A trade union','A loan or bond','d','An amount borrowed, a rate paid on it and a date it is repaid describe a debt instrument.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false),
(t_sci,'both','mcq','Rock layers - fossils - relative age','Stratigraphy','Astronomy','Metallurgy','Meteorology','a','Deeper layers are older, so the fossils they hold can be placed in order of age - the basis of stratigraphy.','medium','YIQ Reasoning Bank 2026 - CONNECT THE CLUES','practice',true,null,true,false);

-- ── VISUAL DETECTIVE ─────────────────────────────────────────────────
-- Spatial reasoning. EVERY question here is answerable from its own
-- words - no media_url, no diagram to render, nothing that can break in
-- a PDF or fail to load on a phone in a school corridor.
insert into yiq.questions (
  topic_id, category, question_type, question_text,
  option_a, option_b, option_c, option_d, correct_option,
  answer_explanation, difficulty, source, pool,
  is_ai_generated, reviewed_at, is_active, is_retired
) values
(t_sci,'both','mcq','In a 5 by 5 grid of cells, how many cells lie on the main diagonal from one corner to the opposite corner?','4','5','10','25','b','The main diagonal of an n by n grid always holds exactly n cells - one in each row.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','A capital L stands upright, its long arm vertical and its short foot pointing right. Rotate it 90 degrees clockwise. The long arm now points:','Left','Up','Right','Down','c','A quarter turn clockwise sends what pointed up to point right. The long arm now lies horizontally to the right.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','A clock reads 3:00. The minute hand then sweeps 120 degrees clockwise. The time shown is now about:','3:15','4:00','3:30','3:20','d','A full circle of 360 degrees is 60 minutes, so 120 degrees is a third of that - 20 minutes.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','Shapes A, B and C have 3, 4 and 5 sides. Going A to B, and then B to C, the sum of the interior angles increases:','Equally in both steps','More from B to C','More from A to B','It does not increase','a','The sum is (sides - 2) times 180: 180, 360, 540. Each extra side adds exactly 180 degrees.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','A balance is level. Two identical circles on one side exactly balance one square on the other. If each circle has a mass of 3 units, the square is:','3','6','5','9','b','Two circles weigh 2 times 3 = 6 units, and the square balances them exactly.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','A graph of value against time rises steeply at first, then more slowly, then almost flattens. Which describes it best?','Growth accelerates throughout','The value falls','Growth slows toward a plateau','The value stays constant','c','Rising but with a shrinking slope means growth continuing at an ever slower rate toward a ceiling.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_india,'both','mcq','The horizontal line of zero degrees latitude divides the globe into which two halves?','Eastern and Western','Tropical and Polar','Land and Ocean','Northern and Southern','d','Zero degrees latitude is the Equator, which separates the Northern and Southern hemispheres. East and West are divided by a line of longitude.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','A cube is painted on all six faces, then cut into 27 identical small cubes. How many have exactly ONE painted face?','6','8','12','27','a','Only the small cube at the centre of each face shows a single painted side - one per face, so six.','hard','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','The same painted cube is cut into 27 small cubes. How many have NO paint at all?','0','1','3','6','b','Only the single cube buried at the very centre never touched an outer face.','hard','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','A cube is painted and cut into 64 identical small cubes. How many have exactly TWO painted faces?','8','16','24','32','c','Two-painted cubes lie along the edges but not at the corners. A cube has 12 edges with 2 such cubes each: 12 times 2 = 24.','hard','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','Six identical squares are laid out in a cross shape and folded along every shared edge. The solid formed is:','A cylinder','A pyramid','A prism with a triangular base','A cube','d','Six squares meeting at right angles close up into a cube. That cross is the most familiar net of one.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','A square is turned about its centre. How many times in one full turn does it look exactly as it started?','4','2','3','1','a','Every quarter turn maps a square onto itself, so it matches four times in 360 degrees.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','How many lines of symmetry does an equilateral triangle have?','1','3','2','6','b','One line runs from each corner to the middle of the opposite side - three in all.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','A rectangle that is NOT a square has how many lines of symmetry?','1','4','2','0','c','Only the two lines through the midpoints of opposite sides. Its diagonals are not lines of symmetry.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','Held to a mirror, the lower-case letter b most resembles:','h','p','q','d','d','A mirror reverses left and right but leaves top and bottom alone, so the bowl of b flips to the other side - giving d.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','In a 4 by 4 grid of small squares, how many squares of ANY size can be traced?','30','20','16','36','a','16 of size one, 9 of size two, 4 of size three and 1 of size four: 16+9+4+1 = 30.','hard','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','In a 3 by 3 arrangement of dots, how many straight lines pass through exactly three dots?','6','8','7','9','b','Three rows, three columns and the two long diagonals: 3+3+2 = 8.','hard','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','Which capital letter looks unchanged when turned upside down (rotated 180 degrees)?','G','F','N','R','c','N maps onto itself under a half turn. F, G and R do not.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','A triangle has angles of 40 and 60 degrees. The third angle is:','60','70','100','80','d','The three angles of a triangle add to 180, so the third is 180 - 40 - 60 = 80.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','Each interior angle of a regular hexagon measures:','120 degrees','108 degrees','90 degrees','135 degrees','a','The interior angles total (6-2) times 180 = 720, shared equally among six corners: 120 each.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','How many diagonals can be drawn inside a pentagon?','4','5','6','10','b','The formula is n(n-3)/2, so 5 times 2 divided by 2 = 5.','hard','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','A cylinder standing upright is viewed from directly above. Its outline is:','A rectangle','A triangle','A circle','An oval','c','Looking straight down the axis you see only the circular end face.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','The same upright cylinder viewed from the side has the outline of:','A circle','A hexagon','A triangle','A rectangle','d','From the side the curved surface projects as a rectangle - its height by its diameter.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','Two identical right-angled triangles are joined along their longest sides. The shape formed is:','A rectangle','A pentagon','A circle','A trapezium with unequal parallel sides','a','Placing the two hypotenuses together turns the pair into a rectangle, since the right angles meet at the corners.','hard','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false),
(t_sci,'both','mcq','The interior angles of any four-sided shape add up to:','180 degrees','360 degrees','270 degrees','540 degrees','b','A quadrilateral splits into two triangles, and 2 times 180 = 360.','medium','YIQ Reasoning Bank 2026 - VISUAL DETECTIVE','practice',true,null,true,false);

-- ── LOGIC LAB ────────────────────────────────────────────────────────
-- Deduction, rates, counting and the classic traps. A Class 9 student and
-- a Class 12 student meet every one of these on identical terms.
insert into yiq.questions (
  topic_id, category, question_type, question_text,
  option_a, option_b, option_c, option_d, correct_option,
  answer_explanation, difficulty, source, pool,
  is_ai_generated, reviewed_at, is_active, is_retired
) values
(t_sci,'both','mcq','A two-digit number has digits adding to 9. Reversing them makes the number 27 larger. The number is:','54','45','36','63','c','If the digits are a and b then reversing changes the value by 9(b-a) = 27, so b-a = 3. With a+b = 9 that gives a=3, b=6 - the number 36.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','5 machines make 5 parts in 5 minutes. How many parts do 20 machines make in 20 minutes?','20','40','100','80','d','One machine takes 5 minutes per part, so in 20 minutes it makes 4. Twenty machines make 20 times 4 = 80.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','Three boxes are labelled APPLES, ORANGES and MIXED. Every label is wrong. To relabel all three correctly, which box should you draw one fruit from?','MIXED','ORANGES','APPLES','Any of them','a','MIXED cannot be mixed, so one fruit identifies it exactly. Because every other label is also wrong, the remaining two then follow with no further draws.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','A 120 m train passes a pole in 6 seconds. How long does it take to pass a 180 m platform?','9 s','15 s','12 s','18 s','b','Passing a pole means covering its own length: 120/6 = 20 m/s. Passing the platform means covering 120+180 = 300 m, which takes 15 s.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','Maya is 15th from the front of a queue and 18th from the back. How many people are in the queue?','31','33','32','34','c','Adding the two positions counts Maya twice: 15 + 18 - 1 = 32.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','A bag holds 4 red, 3 blue and 3 green balls. Drawing blind, how many must you take to be CERTAIN of two the same colour?','3','6','5','4','d','Three draws could give one of each colour. A fourth must repeat one of the three - the pigeonhole principle.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','With A=1 through Z=26, which word has the greatest letter total?','QUIZ','MATH','LOGIC','BRAIN','a','QUIZ = 17+21+9+26 = 73, ahead of LOGIC (46), BRAIN (44) and MATH (42). The late letters carry it.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','All Bloops are Razzies, and all Razzies are Lazzies. Which must be true?','All Lazzies are Bloops','All Bloops are Lazzies','No Bloops are Lazzies','Some Razzies are not Lazzies','b','The chain carries through: every Bloop is a Razzie, and every Razzie is a Lazzie. The reverse does not follow.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','Six people each shake hands once with everyone else. How many handshakes take place?','12','21','15','30','c','Each of 6 shakes 5 hands, giving 30 - but that counts each handshake from both sides, so 30/2 = 15.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','A clock loses 5 minutes every hour. Set correctly at noon, what will it show after 12 real hours?','12:30','11:30','12:00','11:00','d','It loses 5 x 12 = 60 minutes over the 12 hours, so it shows one hour behind midnight - 11:00.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','3 painters take 4 days to paint a house. At the same rate, how long do 6 painters take?','2 days','1 day','3 days','8 days','a','The job is 12 painter-days. Six painters working together finish it in 12/6 = 2 days.','medium','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','Which number does NOT belong: 3, 5, 7, 9, 11?','3','9','7','11','b','All the others are prime. 9 is 3 times 3.','medium','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','All roses are flowers. Some flowers fade quickly. Which follows?','Some roses fade quickly','No roses fade quickly','Nothing about roses follows','All flowers are roses','c','The flowers that fade quickly may be entirely non-roses. Neither conclusion about roses is forced.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','In a race you overtake the runner in second place. What position are you in?','First','Cannot be determined','Third','Second','d','You take the overtaken runner''s place, which was second. Answering first is the classic slip.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','A farmer has 17 sheep. All but 9 die. How many are left?','9','8','17','0','a','All BUT nine died, so the nine are what survived. The number 8 is the trap.','medium','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','How many months of the year have 28 days?','1','12','11','2','b','Every month contains a 28th day. Only February has EXACTLY 28, which is not what was asked.','medium','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','A rope ladder hangs over a ship''s side with rungs 30 cm apart, three rungs above the water. The tide rises 10 cm an hour. After 3 hours, how many rungs are underwater?','1','2','None','3','c','The ship floats and rises with the tide, so the ladder rises with it. The water never reaches a new rung.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','You enter a dark room with one match, holding an oil lamp, a candle and a wood fire. What do you light first?','The lamp','The candle','The fire','The match','d','Nothing can be lit until the match itself is struck.','medium','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','Two fathers and two sons went fishing. Each caught exactly one fish, and only three fish were caught. How?','They were grandfather, father and son','One lied','One fish was shared','The problem is impossible','a','Three people can be two fathers and two sons at once: the middle man is both a father and a son.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','What letter continues the sequence J, F, M, A, M, J, J, A?','T','S','O','N','b','They are the initials of the months. After August comes September.','medium','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','Divide 30 by a half, then add 10. The result is:','25','35','70','40','c','Dividing by a half means multiplying by 2: 30/0.5 = 60, and 60 + 10 = 70. Halving instead gives the trap 25.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','If 5 cats catch 5 mice in 5 minutes, how many cats are needed to catch 100 mice in 100 minutes?','25','20','100','5','d','Each cat catches one mouse per 5 minutes, so in 100 minutes it catches 20. Five cats catch 100.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','A boy has as many sisters as brothers. Each of his sisters has half as many sisters as brothers. How many children are in the family?','7','6','5','8','a','Let there be B boys and G girls. The boy sees G sisters and B-1 brothers, so G = B-1. A girl sees G-1 sisters and B brothers, so G-1 = B/2. Solving gives B=4, G=3 - seven children.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','Three switches outside a sealed room control one bulb inside. You may enter ONCE. How do you identify the right switch?','Guess after flipping one','Turn one on a while, off, turn a second on, then enter and feel the bulb','It cannot be done','Flip all three together','b','Lit means the second switch. Off but warm means the first. Off and cold means the third - heat carries the extra bit of information.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','What comes next: 1, 11, 21, 1211, 111221?','111222','122111','312211','211213','c','Each term describes the one before it aloud. 111221 is read as three ones, two twos, one one - giving 312211.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_econ,'both','mcq','A shopkeeper buys an item for 80 rupees, marks it up 50%, then offers 20% off the marked price. The selling price is:','88','92','100','96','d','The marked price is 80 x 1.5 = 120, and 20% off gives 120 x 0.8 = 96.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','You have 8 identical-looking balls; one is slightly heavier. What is the FEWEST weighings on a balance that guarantees finding it?','2','1','3','4','a','Weigh 3 against 3. If they balance the heavy ball is among the other 2, found in one more. If not, the heavier group of 3 splits 1 against 1. Two weighings always suffice.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','If today is two days after Monday, what day will tomorrow be?','Wednesday','Thursday','Friday','Tuesday','b','Two days after Monday is Wednesday, so tomorrow is Thursday.','medium','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','Which weighs more, a kilogram of iron or a kilogram of cotton?','The iron','The cotton','They weigh the same','It depends on temperature','c','A kilogram is a kilogram. The iron merely occupies far less space, which is what makes it feel heavier.','medium','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','A snail at the bottom of a 10 m well climbs 3 m each day and slips back 2 m each night. On which day does it get out?','Day 11','Day 9','Day 10','Day 8','d','It gains 1 m a day, so it starts day 8 at 7 m. That day it climbs 3 m to reach 10 m and is out before the night slip.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','Ram is Sita''s brother. Sita is Gita''s mother. Ram is Gita''s:','Uncle','Father','Brother','Grandfather','a','Ram is the brother of Gita''s mother, which makes him Gita''s uncle.','medium','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','If PENCIL is written in code as QFODJM, then BOOK is written as:','APNJ','CPPL','CPNL','CQPL','b','Each letter moves one place forward: B to C, O to P, O to P, K to L.','medium','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','No student in the class failed, and some got a distinction. Which MUST be true?','Every student got a distinction','Most students got a distinction','At least some students passed','Nothing can be concluded','c','If nobody failed then everyone passed, so certainly some did. The size of the distinction group is not given.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','A tank fills in 6 hours through one pipe and 12 hours through another. With both open, it fills in:','3 hours','9 hours','8 hours','4 hours','d','In one hour they fill 1/6 + 1/12 = 3/12 = 1/4 of the tank, so the whole tank takes 4 hours.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false),
(t_sci,'both','mcq','Some artists are dreamers. All dreamers are hopeful. Which MUST be true?','Some artists are hopeful','All artists are hopeful','No artist is hopeful','All hopeful people are artists','a','The artists who are dreamers must be hopeful. Nothing is settled about the remaining artists.','hard','YIQ Reasoning Bank 2026 - LOGIC LAB','practice',true,null,true,false);

-- ── THE FINAL CHALLENGE ──────────────────────────────────────────────
-- Multi-step work, probability, and judging evidence. The last section
-- of the source paper and the one that most separates the top teams.
insert into yiq.questions (
  topic_id, category, question_type, question_text,
  option_a, option_b, option_c, option_d, correct_option,
  answer_explanation, difficulty, source, pool,
  is_ai_generated, reviewed_at, is_active, is_retired
) values
(t_econ,'both','mcq','Successive discounts of 20% and then 10% are equal to one single discount of:','30%','28%','32%','18%','b','The price becomes 0.8 x 0.9 = 0.72 of the original, a fall of 28%. Discounts never simply add.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','A fair coin is tossed 4 times. What is the probability of exactly 2 heads?','1/4','1/2','3/8','5/8','c','There are 16 equally likely outcomes and 6 of them contain exactly two heads, giving 6/16 = 3/8.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','Half of a fixed distance is covered at 30 km/h and the other half at 60 km/h. The average speed is:','50 km/h','45 km/h','48 km/h','40 km/h','d','Average speed is total distance over total time. More time is spent on the slow half, so the answer sits below 45: it is 40 km/h.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','Umbrella sales rise when traffic slows, so umbrellas cause traffic jams. What is the best challenge to this?','Rain could be causing both','Umbrellas are small','Traffic never changes','Sales data cannot be numeric','a','A third factor explains both at once. Rain drives up umbrella sales AND slows traffic, so neither causes the other.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','A 3-digit code uses different digits chosen from 1, 2, 3, 4, and the first digit must be even. How many codes are possible?','8','12','10','16','b','The first digit is 2 or 4 (2 ways). The remaining two positions take any 2 of the 3 unused digits in order: 3 x 2 = 6. Total 2 x 6 = 12.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','What is the best evidence that a new study method improves results?','Ask students who liked it','Compare the two top students','Compare a group using it with a similar control group','Ask if scores felt higher','c','Only a comparison against a similar group that did NOT use the method separates the method''s effect from everything else.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','Two fair dice are rolled. The probability that the total is 7 is:','1/12','5/36','1/8','1/6','d','Six of the 36 equally likely pairs total seven, so 6/36 = 1/6. Seven is the most likely total.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','A jar holds 5 red and 5 blue balls. Two are drawn without replacement. The probability both are red is:','2/9','1/4','1/5','5/18','a','The first is red with probability 5/10. With one red gone, the second is red with probability 4/9. Multiplying gives 20/90 = 2/9.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_econ,'both','mcq','1000 rupees is invested at 10% compound interest for 2 years. The amount is:','1100','1210','1200','1220','b','Year one adds 100 to make 1100; year two adds 10% of 1100, which is 110. The total is 1210.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_econ,'both','mcq','On 1000 rupees at 10% for 2 years, by how much does compound interest exceed simple interest?','0','20','10','100','c','Simple interest gives 200; compound gives 210. The 10-rupee gap is the interest earned on the first year''s interest.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','A class averages 60 marks. One more student scoring 80 raises the average to 61. How many students were there BEFORE?','15','21','20','19','d','If n students averaged 60, then (60n + 80)/(n+1) = 61. Solving gives 60n + 80 = 61n + 61, so n = 19.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','To learn how many people in a town have internet access, a researcher surveys people through a smartphone app. The main flaw is:','Everyone surveyed is already online','The sample is too small','Phones give wrong answers','The question is unclear','a','The method can only reach people who already have access, so it cannot possibly find those who do not. That is sampling bias.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','Ice cream sales and drowning deaths rise and fall together across the year. The most likely explanation is:','Ice cream causes drowning','Hot weather raises both','Drowning causes ice cream sales','Pure coincidence with no cause','b','Warm weather independently drives both swimming and ice cream buying. It is a confounding variable, not a link between the two.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','"If it rained, the ground is wet." The ground is NOT wet. What follows?','It rained','It may have rained','It did not rain','Nothing follows','c','If the consequence is false the condition must be false too. This is valid reasoning.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','"If it rained, the ground is wet." The ground IS wet. What follows about rain?','It definitely rained','It definitely did not rain','It rained heavily','Nothing certain - something else could have wet it','d','A sprinkler or a burst pipe would also do it. Concluding rain from a wet ground is the classic invalid step.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','A disease affects 1 person in 10,000. A test is 99% accurate. Someone tests positive. Most likely, that person:','Probably does NOT have the disease','Probably has the disease','Definitely has the disease','Cannot be assessed at all','a','In a million people about 100 have it, but 1% of the other 999,900 - nearly 10,000 people - test positive wrongly. A positive result is far more often a false alarm.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_econ,'both','mcq','A car worth 100,000 rupees loses 20% of its value each year. After 2 years it is worth:','60,000','64,000','68,000','80,000','b','Each year multiplies by 0.8: 100,000 x 0.8 x 0.8 = 64,000. Subtracting 40% outright gives the trap 60,000.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','Which is the stronger evidence that a medicine works?','A letter from a satisfied patient','A famous person endorsing it','A trial where patients were randomly given the medicine or a dummy','The manufacturer''s own claim','c','Random allocation and a comparison group remove the alternative explanations that a single story cannot rule out.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','A study finds students who eat breakfast score higher. Its main weakness is that it:','Used too many students','Should have used older students','Measured scores incorrectly','Cannot show breakfast CAUSED the higher scores','d','Households where breakfast happens may differ in many other ways. Observing a pattern does not establish which way the cause runs.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','With 3 shirts and 4 pairs of trousers, how many different outfits are possible?','12','7','14','24','a','Every shirt can pair with every pair of trousers: 3 x 4 = 12.','medium','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','In how many different orders can the four letters of TEAM be arranged?','12','24','16','48','b','Four choices, then three, then two, then one: 4 x 3 x 2 x 1 = 24. All four letters differ.','medium','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','One card is drawn from a standard 52-card pack. The probability it is an ace is:','1/4','1/26','1/13','4/13','c','There are 4 aces among 52 cards: 4/52 = 1/13.','medium','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','Two independent events have probabilities 0.5 and 0.4. The probability both happen is:','0.1','0.9','0.45','0.2','d','For independent events the probabilities multiply: 0.5 x 0.4 = 0.2.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_econ,'both','mcq','After a 20% discount a shirt costs 500 rupees. Its original price was:','625','600','575','650','a','500 is 80% of the original, so the original is 500/0.8 = 625. Adding 20% back gives the trap 600.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','A 10 m ladder rests against a wall with its base 6 m out. How high up the wall does it reach?','7 m','8 m','9 m','12 m','b','The wall, ground and ladder form a right-angled triangle: 10 squared minus 6 squared is 64, whose square root is 8.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','The sum of the first 50 whole numbers (1 to 50) is:','1225','1250','1275','2550','c','Pair them: 1+50, 2+49 and so on gives 25 pairs of 51, which is 1275.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','A cyclist rides the first third of a journey at 10 km/h and the remaining two thirds at 20 km/h. The average speed is:','13.3 km/h','18 km/h','16.7 km/h','15 km/h','d','Take the trip as 3 km. The first km takes 0.1 h and the next two take 0.1 h - 3 km in 0.2 h, which is 15 km/h.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','An advertisement states "80% of doctors recommend this brand". What matters MOST before believing it?','How many doctors were asked and who paid for the survey','The brand''s colour','Whether it rhymes','How long the brand has existed','a','A percentage without its sample size or its funding source can be produced from a handful of hand-picked people.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','A fair coin is tossed 3 times. The probability of AT LEAST one head is:','1/2','7/8','3/4','5/8','b','The only excluded outcome is three tails, which has probability 1/8. So the answer is 1 - 1/8 = 7/8.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','In a town 40% read paper A, 30% read paper B and 10% read both. What percentage reads at least one?','50%','70%','60%','80%','c','Adding 40 and 30 counts the overlap twice, so subtract it once: 40 + 30 - 10 = 60.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','A rectangle''s length is doubled and its width is halved. Its area is:','Doubled','Halved','Four times larger','Unchanged','d','Area is length times width, and the factors 2 and 1/2 cancel exactly. The perimeter does change.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sport,'both','mcq','Six teams each play every other team once. How many matches are played in total?','15','12','30','36','a','Each of six teams plays five others, giving 30 - but each match is counted from both sides, so 30/2 = 15.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','To gauge the whole school''s opinion, the most representative sample is:','The first 30 students to arrive','30 students chosen at random from every class','30 volunteers','The 30 students with the best marks','b','Random selection across all classes gives every student a comparable chance of being chosen. The other three each select a particular kind of student.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_sci,'both','mcq','A water tank loses 5% of its remaining water each day. After 2 days, roughly what fraction is left?','85%','90%','90.25%','95%','c','Each day multiplies by 0.95: 0.95 x 0.95 = 0.9025, which is 90.25%.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false),
(t_young,'both','mcq','A project claims it "helped over 1,000 young people". Which single detail would tell you the most about whether it worked?','The number reached','The number of photographs taken','The size of the launch event','What changed for them, measured before and after','d','Reach counts people touched, not outcomes. Only a before-and-after measure shows whether anything actually changed.','hard','YIQ Reasoning Bank 2026 - THE FINAL CHALLENGE','practice',true,null,true,false);

end $$;
